apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
type: Opaque
data:
  # Mot de passe: "SuperSecretPassword123" encodé en base64
  DB_PASSWORD: U3VwZXJTZWNyZXRQYXNzd29yZDEyMw==
  